name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - '*.md'
      - 'docs/**'
      - 'LICENSE'

jobs:
  Linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build introcore
      run: |
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        cd ..

  Windows-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Build introcore
      run: MSBuild /t:Rebuild /p:Configuration=Release /p:Platform=x64 hvmi.sln
