name: Build libintrocore and hvmid

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - '*.md'
      - 'docs/**'
      - 'LICENSE'

jobs:
  Linux-build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build introcore
      run: |
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        cd ..
    - name: Install introcore
      run: |
        cd _build
        sudo make install
        cd ..
    - name: Install boost
      run: sudo apt install libboost-dev
    - name: Install libxen-dev
      run: sudo apt install libxen-dev
    - name: Checkout libbdvmi
      uses: actions/checkout@master
      with:
        repository: bitdefender/libbdvmi
        path: libbdvmi
    - name: Build and install libbdvmi
      run: |
        cd libbdvmi
        ./bootstrap
        ./configure
        make -j$(nproc)
        sudo make install
        cd ..
    - name: Checkout libjsoncpp
      uses: actions/checkout@master
      with:
        repository: open-source-parsers/jsoncpp
        path: jsoncpp
    - name: Build and install libjsoncpp
      run: |
        cd jsoncpp
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        sudo make install
        cd ..
        cd ..
    - name: Build hvmid
      run: |
        cd daemon
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        cd .. 

  Windows-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    - name: Build introcore
      run: MSBuild /t:Rebuild /p:Configuration=Release /p:Platform=x64 hvmi.sln
